// USER
export const SIGN_IN_HANDLER = 'SIGN_IN_HANDLER';
export const SIGN_OUT_HANDLER = 'SIGN_OUT_HANDLER';
export const SET_USER_PRODUCTS = 'SET_USER_PRODUCTS';

// PRODUCTS
export const HANDLE_DETAIL = 'HANDLE_DETAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_PRODUCT_FOR_UPDATING_HANDLER = 'SET_PRODUCT_FOR_UPDATING_HANDLER';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const UPDATE_BACKEND_INVENTORY = 'UPDATE_BACKEND_INVENTORY';
export const SET_PRODUCTS = 'SET_PRODUCTS';

// OTHER
export const OPEN_MODAL_HANDLER = 'OPEN_MODAL_HANDLER';
export const CLOSE_MODAL_HANDLER = 'CLOSE_MODAL_HANDLER';
export const SET_ERROR_HANDLER = 'SET_ERROR_HANDLER';
export const TOGGLE_ERROR_MODAL_HANDLER = 'TOGGLE_ERROR_MODAL_HANDLER';
export const COMPILE_TOTAL_VALUES_HANDLER = 'COMPILE_TOTAL_VALUES_HANDLER';
export const VALIDATION_HANDLER = 'VALIDATION_HANDLER';
export const RESET_FILE_HANDLER = 'RESET_FILE_HANDLER';
export const TOGGLE_LOADING_STATE = 'TOGGLE_LOADING_STATE';